import {getOpenAI} from './openai'
import {jobSchema,matchSchema,resumeProfileSchema} from './schemas'
const model=()=>process.env.OPENAI_MODEL||'gpt-5.6-luna'

const jobJson={type:'object',properties:{company:{type:'string'},title:{type:'string'},job_id:{type:['string','null']},location:{type:'string'},job_url:{type:'string'},job_family:{type:'string'},required_skills:{type:'array',items:{type:'string'}},preferred_skills:{type:'array',items:{type:'string'}},experience_requirements:{type:'string'},responsibilities:{type:'array',items:{type:'string'}},education_certifications:{type:'array',items:{type:'string'}},keywords:{type:'array',items:{type:'string'}},work_authorization:{type:'array',items:{type:'string'}},other_requirements:{type:'array',items:{type:'string'}}},required:['company','title','job_id','location','job_url','job_family','required_skills','preferred_skills','experience_requirements','responsibilities','education_certifications','keywords','work_authorization','other_requirements'],additionalProperties:false}
const profileJson={type:'object',properties:{name:{type:'string'},primary_positioning:{type:'string'},job_titles:{type:'array',items:{type:'string'}},seniority:{type:'string'},years_experience:{type:'string'},job_families:{type:'array',items:{type:'string'}},skills:{type:'array',items:{type:'string'}},industries_domains:{type:'array',items:{type:'string'}},education_certifications:{type:'array',items:{type:'string'}},achievements_projects:{type:'array',items:{type:'string'}},keywords:{type:'array',items:{type:'string'}},evidence:{type:'array',items:{type:'string'}}},required:['name','primary_positioning','job_titles','seniority','years_experience','job_families','skills','industries_domains','education_certifications','achievements_projects','keywords','evidence'],additionalProperties:false}
const matchJson={type:'object',properties:{score:{type:'number'},classification:{type:'string',enum:['Strong match','Moderate / caution','Poor match']},required_skills_score:{type:'number'},relevant_experience_score:{type:'number'},responsibilities_score:{type:'number'},seniority_score:{type:'number'},industry_score:{type:'number'},preferred_skills_score:{type:'number'},job_family_fit_score:{type:'number'},evidence:{type:'array',items:{type:'string'}},strengths:{type:'array',items:{type:'string'}},gaps:{type:'array',items:{type:'string'}},deal_breakers:{type:'array',items:{type:'string'}},reason:{type:'string'}},required:['score','classification','required_skills_score','relevant_experience_score','responsibilities_score','seniority_score','industry_score','preferred_skills_score','job_family_fit_score','evidence','strengths','gaps','deal_breakers','reason'],additionalProperties:false}

export async function extractJob(page:{title:string;text:string;jsonLd:any[]},url:string){const r=await getOpenAI().responses.create({model:model(),input:`Extract a structured job profile. Do not invent missing fields. Separate required from preferred skills. Explicitly capture work authorization/visa language when stated. Use job family from: Software Engineer, Backend / API, Full Stack, Frontend, .NET / C#, Node.js / JavaScript, Data Analyst / BI, Data Scientist, ML Engineer / Data Engineer, Controls / Automation, Cloud / DevOps, General / Other.\n\nTitle:${page.title}\nJSON-LD:${JSON.stringify(page.jsonLd).slice(0,18000)}\nPage text:${page.text}`,text:{format:{type:'json_schema',name:'job_profile',strict:true,schema:jobJson}}});const x=jobSchema.parse(JSON.parse(r.output_text));x.job_url=url;return x}

export async function profileResume(text:string,filename:string){const r=await getOpenAI().responses.create({model:model(),input:`Create a structured profile for this resume. Do not invent experience, skills, seniority, dates, or qualifications. Use only evidence present in the resume. Filename: ${filename}\n\n${text.slice(0,40000)}`,text:{format:{type:'json_schema',name:'resume_profile',strict:true,schema:profileJson}}});return resumeProfileSchema.parse(JSON.parse(r.output_text))}

export async function matchResume(job:any,resume:any){const r=await getOpenAI().responses.create({model:model(),input:`Evaluate this resume for the job. Never invent experience. First identify hard qualification failures: mandatory skills, minimum experience, required education/certification, work authorization/visa, or other explicit requirements. Then score: required skills 35%, relevant experience 25%, responsibilities 15%, seniority/title 10%, industry/domain 5%, preferred skills 5%, job-family/profile fit 5%. A missing mandatory requirement must be a deal-breaker and materially reduce the score. Every important claim should have evidence from the resume profile.\n\nJOB:\n${JSON.stringify(job)}\n\nRESUME:\n${JSON.stringify(resume)}`,text:{format:{type:'json_schema',name:'resume_match',strict:true,schema:matchJson}}});return matchSchema.parse(JSON.parse(r.output_text))}
